name: Bitacora Web - Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy en Windows Server
    runs-on: self-hosted

    steps:
      - name: Información del servidor
        shell: powershell
        run: |
          Write-Host "===== USUARIO ====="
          whoami

          Write-Host "===== PYTHON ====="
          python --version

          Write-Host "===== GIT ====="
          git --version

      - name: Información del proyecto
        shell: powershell
        run: |
          Set-Location "C:\wamp64\www\bitacora_web-main"

          Write-Host "===== DIRECTORIO ====="
          Get-Location

          Write-Host "===== GIT STATUS ====="
          git status

          Write-Host "===== BRANCH ====="
          git branch --show-current

      - name: Comprobar Django
        shell: powershell
        run: |
          Set-Location "C:\wamp64\www\bitacora_web-main"

          .\.venv\Scripts\python.exe --version

          .\.venv\Scripts\python.exe -m django --version

          .\.venv\Scripts\python.exe manage.py check